version: '3'

services:
  product-service:
    build: ./product-service
    image: franklynux/product-service:latest
    ports:
      - "8001:8000"
    volumes:
      - ./product-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app

  cart-service:
    build: ./cart-service
    image: franklynux/cart-service:latest
    ports:
      - "8002:8000"
    volumes:
      - ./cart-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
      - PRODUCT_SERVICE_URL=http://product-service:8000

  order-service:
    build: ./order-service
    image: franklynux/order-service:latest
    ports:
      - "8003:8000"
    volumes:
      - ./order-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
      - CART_SERVICE_URL=http://cart-service:8000
      - PRODUCT_SERVICE_URL=http://product-service:8000