# Module with diagnostics UI enabled
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
  namespace: emissary
spec:
  config:
    diagnostics:
      enabled: true
---
# Host using wildcard
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: ecommerce-host
  namespace: emissary
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route