apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: product-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /products/
  service: product-service.ecommerce:8000
  timeout_ms: 30000
  connect_timeout_ms: 10000
  retry_policy:
    retry_on: 5xx
    num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: cart-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /carts/
  service: cart-service.ecommerce:8000
  timeout_ms: 30000
  connect_timeout_ms: 10000
  retry_policy:
    retry_on: 5xx
    num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: order-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /orders/
  service: order-service.ecommerce:8000
  timeout_ms: 30000
  connect_timeout_ms: 10000
  retry_policy:
    retry_on: 5xx
    num_retries: 3