# Product-service mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: product-service-mapping
  namespace: ecommerce
spec:
  prefix: /products/
  service: product-service:8000
  rewrite: ""
---
# Cart-service mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: cart-service-mapping
  namespace: ecommerce
spec:
  prefix: /carts/
  service: cart-service:8000
  rewrite: ""
---
# Order-service mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: order-service-mapping
  namespace: ecommerce
spec:
  prefix: /orders/
  service: order-service:8000
  rewrite: ""