apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: product-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /products/
  service: product-service.ecommerce:8000
  cors:
    origins:
      - "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - Content-Type
      - Authorization
    credentials: true
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: cart-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /carts/
  service: cart-service.ecommerce:8000
  cors:
    origins:
      - "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - Content-Type
      - Authorization
    credentials: true
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: order-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /orders/
  service: order-service.ecommerce:8000
  cors:
    origins:
      - "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - Content-Type
      - Authorization
    credentials: true