apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    monitor: "true"
spec:
  selector:
    app: cart-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP