# Product, Cart and Order Microservices
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: product-api
            service: product-service
          - name: cart-api
            service: cart-service
          - name: order-api
            service: order-service
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/franklynux/ecommerce-platform-microservice-architecture.git
        targetRevision: HEAD
        path: k8s/{{service}}
      destination:
        server: https://kubernetes.default.svc
        namespace: ecommerce
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true