# Emissary-Ingress Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/franklynux/ecommerce-platform-microservice-architecture.git
    targetRevision: HEAD
    path: k8s
    directory:
      include: "emissary-ingress.yaml,ingress.yaml,emissary-listener.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: emissary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true